# Generated by Django 5.0.2 on 2024-02-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
